name: gluten_freemwork
description: robotlegs port to flutter
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  organic_injection:
    path: ../organic_injection


dev_dependencies:
  test: ^0.12.0



